### ISSUE TITLE
Test : can send problem

### ISSUE THREAD

**Issue by euberdeveloper** [eagletrt/telemetria-sender#8]
There was a problem discovered by @Bonnee  @mattebit  @zabealbe  and that I did not remember. Make them pass you the code that revealed that problem, change it if you need to and add a test to the "parziali" to check that it is solved.

**Comment by mattebit** [comment]
We found that using canReceiveSimple function of [utils/can_utils/can_utils.c](can_utils.c) we got segmentation fault sometimes, we think that was due to the malloc in the function.

**Comment by euberdeveloper** [comment]
Have you got the C code that you used? @mattebit

**Comment by mattebit** [comment]
I think i used the same version as the one that is on the repo.

**Comment by Bonnee** [comment]
I don't remember the problem, but I believe it was related to the malloc call inside the function. I would take that call outside of the function, to avoid accidental memory leaks

**Comment by euberdeveloper** [comment]
@mattebit do you have the piece of code that failed?

**Comment by mattebit** [comment]
int canReceiveSimple(int socket, char** data) {
	struct can_frame frame_read;
	int result = read(socket, &frame_read, 16);

	***data = (char*) malloc(frame_read.can_dlc * sizeof(char));**

	for (int i = 0; i < frame_read.can_dlc; ++i) {
		(*data)[i] = frame_read.data[i];
	}

	return result;
}

**Comment by nicolatoscan** [comment]
@mattebit do you also have the code where you used canReceiveSimple and got a segmentation fault?

**Comment by mattebit** [comment]
[test_can.txt](https://github.com/eagletrt/telemetria-sender/files/6443283/test_can.txt)

This was the code we used, i remember that if we used the canReciveSimple() function even without doing anything else, when receiving a can message we got segmentation fault

**Comment by nicolatoscan** [comment]
You should change your code from:
```c
char **data;
canReceiveSimple(socket, data);
```
to:
```c
char *data;
canReceiveSimple(socket, &data);
```
